<?php $this->inlineScript()->prependFile($this->basePath() . '/js/kmb.mmgr.modules.js'); ?>
<a id="btn-add-module" class="btn btn-info btn-xs pull-right disabled" title="<?php echo $this->translate('Add a module') ?>" data-toggle="modal" data-target="#add-module">
    <span class="glyphicon glyphicon-hourglass"></span>
    <?php echo $this->translate('Add') ?>
</a>
<div id="add-module" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="addModuleLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h1 class="modal-title" id="addModuleLabel"><?php echo $this->translate('Add a module') ?></h1>
            </div>
            <form role="form" id="add-module-form" action="<?php echo $this->url('module-manager-modules', ['action' => 'install'], [], true) ?>" method="post">
                <div class="modal-body">
                    <blockquote style="margin-top: 16px">
                        <p><?php echo $this->translate('You can add any released version or any branch of a module.') ?></p>
                    </blockquote>
                    <div class="form-group">
                        <label for="module"><?php echo $this->translate('Module') ?></label>
                        <select id="module" data-placeholder="<?php echo $this->translate('Choose a module...') ?>" class="form-control" name="module" data-rel="chosen">
                            <option value=""></option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="version"><?php echo $this->translate('Version') ?></label>
                        <select id="version" data-placeholder="<?php echo $this->translate('Select a version...') ?>" class="form-control" name="version" data-rel="chosen">
                            <option value=""></option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Cancel') ?></button>
                    <button type="submit" class="btn btn-primary"><?php echo $this->translate('Save') ?></button>
                </div>
            </form>
        </div>
    </div>
</div>
