<?php $this->inlineScript()->prependFile($this->basePath() . '/js/kmb.module.manager.js'); ?>
<a class="btn btn-info btn-xs pull-right<?php if (!isset($this->puppetModules)): ?> disabled<?php endif ?>" data-toggle="modal" data-target="#add-module">
    <span class="glyphicon glyphicon-plus-sign"></span>
    <?php echo $this->translate('Add a module') ?>
</a>
<div id="add-module" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="addModuleLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h1 class="modal-title" id="addModuleLabel"><?php echo $this->translate('Add a module') ?></h1>
            </div>
            <form role="form" action="<?php echo $this->url('module-manager-modules', ['action' => 'add'], [], true) ?>" method="post">
                <div class="modal-body">
                    <blockquote style="margin-top: 16px">
                        <p><?php echo $this->translate('You can add any released version or any branch of a module.') ?></p>
                    </blockquote>
                    <div class="form-group">
                        <label for="create-group-name"><?php echo $this->translate('Choose a name') ?></label>
                        <input type="text" class="form-control" name="name" id="create-group-name" />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Cancel') ?></button>
                    <button type="submit" class="btn btn-primary"><?php echo $this->translate('Save') ?></button>
                </div>
            </form>
        </div>
    </div>
</div>
