<?php $this->inlineScript()->prependFile($this->basePath() . '/js/kmb.mmgr.module.js'); ?>
<div class="col-md-2 info-bar pull-right">
    <div class="green">&nbsp;</div>
    <div class="update-btn">
        <a class="btn btn-success" title="<?php echo $this->translate('Update the module') ?>" data-toggle="modal" data-target="#update-module" data-version-href="<?php echo $this->url('module-manager-module', ['action' => 'versions', 'name' => $this->module->getName()], [], true) ?>">
            <span class="glyphicon glyphicon-refresh"></span>
            <?php echo $this->translate('Update') ?>
        </a>
    </div>
</div>
<div class="col-md-2 info-bar pull-right">
    <div class="red">&nbsp;</div>
    <div class="remove-btn">
        <a class="btn btn-danger" href="#" title="<?php echo $this->translate('Remove the module') ?>" data-href="<?php echo $this->url('module-manager-module', ['action' => 'remove', 'name' => $this->module->getName()], [], true) ?>" data-toggle="modal" data-target="#confirm-remove" data-confirm-param1="<?php echo $this->module->getName() ?>" data-confirm-param2="<?php echo $this->environment->getNormalizedName() ?>">
            <span class="glyphicon glyphicon-remove-sign"></span>
            <?php echo $this->translate('Remove') ?>
        </a>
    </div>
</div>
<div id="update-module" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="updateModuleLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h1 class="modal-title" id="updateModuleLabel"><?php echo $this->translate('Update the module') ?></h1>
            </div>
            <form role="form" action="<?php echo $this->url('module-manager-modules', ['action' => 'install'], [], true) ?>" method="post">
                <div class="modal-body">
                    <blockquote style="margin-top: 16px">
                        <p><?php echo $this->translate('You can update the module with any available branch or released version.') ?></p>
                    </blockquote>
                    <div class="form-group">
                        <label for="version"><?php echo $this->translate('Version') ?></label>
                        <select id="version" data-placeholder="<?php echo $this->translate('Select a version...') ?>" class="form-control" name="version" data-rel="chosen">
                            <option value=""></option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Cancel') ?></button>
                    <button type="submit" class="btn btn-primary"><?php echo $this->translate('Save') ?></button>
                </div>
            </form>
        </div>
    </div>
</div>
<div id="confirm-remove" class="modal fade confirm" tabindex="-1" role="dialog" aria-labelledby="confirmRemoveLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h1 class="modal-title" id="confirmRemoveLabel"><?php echo $this->translate('Confirm Remove') ?></h1>
            </div>
            <div class="modal-body">
                <blockquote>
                    <p><?php echo sprintf($this->translate('You are about to remove %s module from %s environment.'), '<strong class="confirm-param1"></strong>', '<strong class="confirm-param2"></strong>') ?></p>
                    <p><?php echo $this->translate('Do you want to proceed ?') ?></p>
                </blockquote>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Cancel') ?></button>
                <a href="#" class="btn btn-danger danger"><?php echo $this->translate('Remove') ?></a>
            </div>
        </div>
    </div>
</div>
